"""Remove foreign key from user_id in users_speech_history

Revision ID: 3ee694e0ffb7
Revises: 0b14f317e826
Create Date: 2024-11-25 22:06:22.207432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ee694e0ffb7'
down_revision: Union[str, None] = '0b14f317e826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_speech_history_user_id_fkey', 'users_speech_history', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('users_speech_history_user_id_fkey', 'users_speech_history', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
